# 1- Charger le datasetdepuis fichier csv

In [290]:
import pandas as pd

data = pd.read_csv("../Airbnb_Open_Data.csv", low_memory = False)

In [291]:
#afficher les 10 premiere line du dataframe
data.head(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN

In [292]:
##afficher les 10 dernieres line du dataframe
data.tail(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
102589,6089676,Lrg room 1 block from Prospect Park,74549151787,unconfirmed,Dave,Brooklyn,Flatbush,40.65231,-73.96189,United States,...,$61,3.0,0.0,NaN,NaN,1.0,1.0,200.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,$50,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN
102591,6090781,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,...,$228,5.0,17.0,1/4/2019,0.35,5.0,1.0,134.0,#NAME?,NaN
102592,6091333,3BR/1 Ba in TriBeCa w/ outdoor deck,53266862889,unconfirmed,Nick,Manhattan,Tribeca,40.71845,-74.01183,United States,...,$157,1.0,0.0,NaN,NaN,2.0,1.0,177.0,Guests should treat my home as if it were thei...,NaN
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [293]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 20.4+ MB

In [294]:
data["license"]

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
102594    NaN
102595    NaN
102596    NaN
102597    NaN
102598    NaN
Name: license, Length: 102599, dtype: str

# 2 Nettoyage des données

In [295]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [296]:
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [297]:
data.duplicated().sum()

np.int64(541)

In [298]:
data.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [299]:
data.drop_duplicates(inplace = True)
#inplace true means work on the same dataframe and not return a new one
data.duplicated().sum()

np.int64(0)

### Remove the NAN values from the dataset

In [300]:
data.isna().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            404
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       400
number of reviews                    183
last review                        15832
reviews per month                  15818
review rate number                   319
calculated host listings count       319
availability 365                     448
house_rules                        51842
license                           102056
dtype: int64

In [301]:
#because the last review column has a lot of missing values we will drop it
data.drop(columns = ["last review"], inplace = True)

In [302]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 102058 entries, 0 to 102057
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102058 non-null  int64
 1   NAME                            101808 non-null  str
 2   host id                         102058 non-null  int64
 3   host_identity_verified          101769 non-null  str
 4   host name                       101654 non-null  str
 5   neighbourhood group             102029 non-null  str
 6   neighbourhood                   102042 non-null  str
 7   lat                             102050 non-null  float64
 8   long                            102050 non-null  float64
 9   country                         101526 non-null  str
 10  country code                    101927 non-null  str
 11  instant_bookable                101953 non-null  object
 12  cancellation_policy             101982 non-null  str
 13  room type                       102058 non-null  str
 14  Construction year               101844 non-null  float64
 15  price                           101811 non-null  str
 16  service fee                     101785 non-null  str
 17  minimum nights                  101658 non-null  float64
 18  number of reviews               101875 non-null  float64
 19  reviews per month               86240 non-null   float64
 20  review rate number              101739 non-null  float64
 21  calculated host listings count  101739 non-null  float64
 22  availability 365                101610 non-null  float64
 23  house_rules                     50216 non-null   str
 24  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(13)
memory usage: 19.5+ MB

In [303]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,...,$696,NaN,7.0,12.0,0.44,5.0,1.0,0.0,Shoes off Clean After yourself Turn Lights and...,NaN
102054,57365760,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,...,$909,NaN,1.0,19.0,0.72,3.0,2.0,0.0,#NAME?,NaN
102055,57366313,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,...,$387,NaN,2.0,50.0,3.12,4.0,2.0,235.0,* Check out: 10am * We made an effort to keep ...,NaN
102056,57366865,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,...,$848,NaN,2.0,0.0,NaN,1.0,1.0,0.0,Each of us is working and/or going to school a...,NaN
102057,57367417,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,...,"$1,128",NaN,4.0,22.0,0.85,4.0,1.0,238.0,Please remember that this is a residential bui...,NaN

In [304]:
data.drop(columns = ["NAME"], inplace = True)
#i deleted because it is just for marketing can't help us in our analysis

In [305]:
# Check Unique Values for each variable.
for i in data.columns.tolist():
  print(f"Number of unique values in {i} is {data[i].nunique()}")

Number of unique values in id is 102058
Number of unique values in host id is 102057
Number of unique values in host_identity_verified is 2
Number of unique values in host name is 13190
Number of unique values in neighbourhood group is 7
Number of unique values in neighbourhood is 224
Number of unique values in lat is 21991
Number of unique values in long is 17774
Number of unique values in country is 1
Number of unique values in country code is 1
Number of unique values in instant_bookable is 2
Number of unique values in cancellation_policy is 3
Number of unique values in room type is 4
Number of unique values in Construction year is 20
Number of unique values in price is 1151
Number of unique values in service fee is 231
Number of unique values in minimum nights is 153
Number of unique values in number of reviews is 476
Number of unique values in reviews per month is 1016
Number of unique values in review rate number is 5
Number of unique values in calculated host listings count is 78
Number of unique values in availability 365 is 438
Number of unique values in house_rules is 1976
Number of unique values in license is 1

In [306]:
data["host_identity_verified"].value_counts()

host_identity_verified
unconfirmed    50944
verified       50825
Name: count, dtype: int64

In [307]:
data["host_identity_verified"].mode()

0    unconfirmed
Name: host_identity_verified, dtype: str

In [308]:
#data["host_identity_verified"].fillna(data["host_identity_verified"].mode()[0], inplace = True)
data["host_identity_verified"] = data["host_identity_verified"].fillna("unconfirmed")

In [309]:
data.drop(columns=["host name"], inplace = True)

In [310]:
data.drop(columns = ["neighbourhood group"], inplace = True)

In [311]:
data.drop(columns = ["neighbourhood"], inplace = True)

In [312]:
data.drop(columns = ["lat", "long"], inplace = True)

In [313]:
data.drop(columns = ["country","country code"], inplace = True)
#i deleted it because it has one value only

In [314]:
# data["instant_bookable"].fillna(data["instant_bookable"].mode()[0], inplace = True) inplace true didn't work i don't know why
data["instant_bookable"] = data["instant_bookable"].fillna(data["instant_bookable"].mode()[0])

In [315]:
data.isna().sum()

id                                     0
host id                                0
host_identity_verified                 0
instant_bookable                       0
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       400
number of reviews                    183
reviews per month                  15818
review rate number                   319
calculated host listings count       319
availability 365                     448
house_rules                        51842
license                           102056
dtype: int64

In [316]:
#categorical variable
data["cancellation_policy"] = data["cancellation_policy"].fillna(data["cancellation_policy"].mode()[0])

In [317]:
data["Construction year"] = data["Construction year"].fillna(data["Construction year"].mean())
data["Construction year"]= data["Construction year"].astype(int)
data

,id,host id,host_identity_verified,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,80014485718,unconfirmed,False,strict,Private room,2020,$966,$193,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,52335172823,verified,False,moderate,Entire home/apt,2007,$142,$28,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,78829239556,unconfirmed,True,flexible,Private room,2005,$620,$124,3.0,0.0,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,85098326012,unconfirmed,True,moderate,Entire home/apt,2005,$368,$74,30.0,270.0,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,92037596077,verified,False,moderate,Entire home/apt,2009,$204,$41,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,77326652202,unconfirmed,True,moderate,Private room,2012,$696,NaN,7.0,12.0,0.44,5.0,1.0,0.0,Shoes off Clean After yourself Turn Lights and...,NaN
102054,57365760,45936254757,verified,False,flexible,Private room,2012,$909,NaN,1.0,19.0,0.72,3.0,2.0,0.0,#NAME?,NaN
102055,57366313,23801060917,verified,True,moderate,Entire home/apt,2012,$387,NaN,2.0,50.0,3.12,4.0,2.0,235.0,* Check out: 10am * We made an effort to keep ...,NaN
102056,57366865,15593031571,unconfirmed,True,strict,Private room,2012,$848,NaN,2.0,0.0,NaN,1.0,1.0,0.0,Each of us is working and/or going to school a...,NaN
102057,57367417,93578954226,verified,False,flexible,Entire home/apt,2011,"$1,128",NaN,4.0,22.0,0.85,4.0,1.0,238.0,Please remember that this is a residential bui...,NaN

In [318]:
#mean when the destribution is normal and median when the distribution is deferent some so big and some so small
data["price"] = (
    data["price"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(" ", "", regex=False)
)
data["price"] = data["price"].astype(float)
data

,id,host id,host_identity_verified,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,80014485718,unconfirmed,False,strict,Private room,2020,966.0,$193,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,52335172823,verified,False,moderate,Entire home/apt,2007,142.0,$28,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,78829239556,unconfirmed,True,flexible,Private room,2005,620.0,$124,3.0,0.0,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,85098326012,unconfirmed,True,moderate,Entire home/apt,2005,368.0,$74,30.0,270.0,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,92037596077,verified,False,moderate,Entire home/apt,2009,204.0,$41,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,77326652202,unconfirmed,True,moderate,Private room,2012,696.0,NaN,7.0,12.0,0.44,5.0,1.0,0.0,Shoes off Clean After yourself Turn Lights and...,NaN
102054,57365760,45936254757,verified,False,flexible,Private room,2012,909.0,NaN,1.0,19.0,0.72,3.0,2.0,0.0,#NAME?,NaN
102055,57366313,23801060917,verified,True,moderate,Entire home/apt,2012,387.0,NaN,2.0,50.0,3.12,4.0,2.0,235.0,* Check out: 10am * We made an effort to keep ...,NaN
102056,57366865,15593031571,unconfirmed,True,strict,Private room,2012,848.0,NaN,2.0,0.0,NaN,1.0,1.0,0.0,Each of us is working and/or going to school a...,NaN
102057,57367417,93578954226,verified,False,flexible,Entire home/apt,2011,1128.0,NaN,4.0,22.0,0.85,4.0,1.0,238.0,Please remember that this is a residential bui...,NaN

In [319]:
# Get summary stats for non-null values
stats = data['price'].describe()
skew = data['price'].skew()

print(f"Mean: {stats['mean']}, Median: {stats['50%']}, Skew: {skew}")

# Decision logic
if abs(skew) < 0.5:
    print("Strategy: Mean (Symmetric)")
else:
    print("Strategy: Median (Skewed)")

Mean: 625.355580438263, Median: 625.0, Skew: 0.0010715047083221104
Strategy: Mean (Symmetric)

In [320]:
data["price"] = data["price"].fillna(data["price"].mean())
data["service fee"] = (
    data["service fee"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(" ", "", regex=False)
)
data["service fee"] = data["service fee"].astype(float)

# Get summary stats for non-null values
stats = data['service fee'].describe()
skew = data['service fee'].skew()

print(f"Mean: {stats['mean']}, Median: {stats['50%']}, Skew: {skew}")

# Decision logic
if abs(skew) < 0.5:
    print("Strategy: Mean (Symmetric)")
else:
    print("Strategy: Median (Skewed)")

Mean: 125.0392493982414, Median: 125.0, Skew: 0.0017217337489740503
Strategy: Mean (Symmetric)

In [321]:
data["service fee"] = data["service fee"].fillna(data["service fee"].mean())
data

,id,host id,host_identity_verified,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,80014485718,unconfirmed,False,strict,Private room,2020,966.0,193.000000,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,52335172823,verified,False,moderate,Entire home/apt,2007,142.0,28.000000,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,78829239556,unconfirmed,True,flexible,Private room,2005,620.0,124.000000,3.0,0.0,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,85098326012,unconfirmed,True,moderate,Entire home/apt,2005,368.0,74.000000,30.0,270.0,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,92037596077,verified,False,moderate,Entire home/apt,2009,204.0,41.000000,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,77326652202,unconfirmed,True,moderate,Private room,2012,696.0,125.039249,7.0,12.0,0.44,5.0,1.0,0.0,Shoes off Clean After yourself Turn Lights and...,NaN
102054,57365760,45936254757,verified,False,flexible,Private room,2012,909.0,125.039249,1.0,19.0,0.72,3.0,2.0,0.0,#NAME?,NaN
102055,57366313,23801060917,verified,True,moderate,Entire home/apt,2012,387.0,125.039249,2.0,50.0,3.12,4.0,2.0,235.0,* Check out: 10am * We made an effort to keep ...,NaN
102056,57366865,15593031571,unconfirmed,True,strict,Private room,2012,848.0,125.039249,2.0,0.0,NaN,1.0,1.0,0.0,Each of us is working and/or going to school a...,NaN
102057,57367417,93578954226,verified,False,flexible,Entire home/apt,2011,1128.0,125.039249,4.0,22.0,0.85,4.0,1.0,238.0,Please remember that this is a residential bui...,NaN

In [322]:
data.isna().sum()

id                                     0
host id                                0
host_identity_verified                 0
instant_bookable                       0
cancellation_policy                    0
room type                              0
Construction year                      0
price                                  0
service fee                            0
minimum nights                       400
number of reviews                    183
reviews per month                  15818
review rate number                   319
calculated host listings count       319
availability 365                     448
house_rules                        51842
license                           102056
dtype: int64

In [323]:
data["minimum nights"] = data["minimum nights"].fillna(data["minimum nights"].mean())
#convert to int
data["minimum nights"] = data["minimum nights"].astype(int)

In [324]:
# number of reviews because some columnes have 0.0
data["number of reviews"] = data["number of reviews"].fillna(0.0)
data["reviews per month"] = data["reviews per month"].fillna(0.0)

In [325]:
data["review rate number"]= data["review rate number"].fillna(2.5)

In [326]:
data["calculated host listings count"] = data["calculated host listings count"].fillna(1.0)

In [327]:
data.isna().sum()

id                                     0
host id                                0
host_identity_verified                 0
instant_bookable                       0
cancellation_policy                    0
room type                              0
Construction year                      0
price                                  0
service fee                            0
minimum nights                         0
number of reviews                      0
reviews per month                      0
review rate number                     0
calculated host listings count         0
availability 365                     448
house_rules                        51842
license                           102056
dtype: int64

In [328]:
data.drop(columns = ["id","host id","availability 365","house_rules","license"], inplace = True)
data

,host_identity_verified,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count
0,unconfirmed,False,strict,Private room,2020,966.0,193.000000,10,9.0,0.21,4.0,6.0
1,verified,False,moderate,Entire home/apt,2007,142.0,28.000000,30,45.0,0.38,4.0,2.0
2,unconfirmed,True,flexible,Private room,2005,620.0,124.000000,3,0.0,0.00,5.0,1.0
3,unconfirmed,True,moderate,Entire home/apt,2005,368.0,74.000000,30,270.0,4.64,4.0,1.0
4,verified,False,moderate,Entire home/apt,2009,204.0,41.000000,10,9.0,0.10,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
102053,unconfirmed,True,moderate,Private room,2012,696.0,125.039249,7,12.0,0.44,5.0,1.0
102054,verified,False,flexible,Private room,2012,909.0,125.039249,1,19.0,0.72,3.0,2.0
102055,verified,True,moderate,Entire home/apt,2012,387.0,125.039249,2,50.0,3.12,4.0,2.0
102056,unconfirmed,True,strict,Private room,2012,848.0,125.039249,2,0.0,0.00,1.0,1.0
102057,verified,False,flexible,Entire home/apt,2011,1128.0,125.039249,4,22.0,0.85,4.0,1.0

In [329]:
data.isna().sum()

host_identity_verified            0
instant_bookable                  0
cancellation_policy               0
room type                         0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
reviews per month                 0
review rate number                0
calculated host listings count    0
dtype: int64